[package]
name = "parallel_brute_force"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"

[dependencies]
criterion = "0.3"
rayon = "1.3"
sha2 = "0.8"

[[bench]]
name = "main"
harness = false