[package]
name = "hundred_prisoners"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
criterion = "0.3"
rayon = "1.3"

[[bench]]
name = "main"
harness = false